language: node_js
node_js:
  - "0.12"
addons:
  sauce_connect: true
before_script:
 - mysql -e 'create database acad_db;'
 - bundle install --gemfile=test/acceptance/Gemfile
 - cp local.json-travis local.json
 - npm start &
 - sleep 5
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    # SauceLabs credentials
    - secure: LIYB2NAtft2PtYgRtBvti6HA24whoOz2NjFntMtpChaJj4+LUyUFjcTtBGcDYh2I2DzG2cY/Q3OqsqMEiTd8qKHRiCKaMW/YNT3bMOTzK6VpoMVj9XFrARUKSQ5rOywn7oY+CCCjcT59FCf6V4LE3OcLX3ABbqGoD4MQTLJoL0A=
    - secure: Vg/Bm+Rh14K9iUhuRvl1hHJNh5uv3pxLS7dPq02pR/8SWzVBrlE55bOV09X3gRa/9JWMv0I4U9sSg9rbclsdaklxO05DVf3yV0EBEEUSlK6kzp1K5jX/rSNpH2+kJnIcBwXVLuKVqnZPumalKNInHJLyTjf5J0/mq6iQIolHaAs=
